### ISSUE TITLE
Interface or manager class for handling all screen interactions

### ISSUE THREAD

**Issue by patricioGarzon** [s1hagog/TaskManagerRepo#4]
a manager class should be introduced to close, open and pass information between screens.

**Comment by s1hagog** [comment]
To transfer information between screen just parse class to the screen class.
Sample is in transfer from MainLoginScreen to UserInfoScreen. We need to parse all the information about the user to UserInfoScreen so we just add User instance as an argument ----> new UserInfoScreen(User user)

**Comment by s1hagog** [comment]
all the classes and interfaces are created
